### ISSUE TITLE
Please parse dates in different languages

### ISSUE THREAD

**Issue by nomeata** [ownaginatious/fbchat-archive-parser#13]
I just came across your useful tool. Thanks! I would like to run it now only on my latest download, but also on archived versions of Facebook zip files, so I cannot change my locale for that,.

It would be great if the tool could parse dates in any locale, or in a given one.

**Comment by nomeata** [comment]
https://dateparser.readthedocs.io/en/latest/ might just be what you need

**Comment by nomeata** [comment]
Indeed
```
def parse_timestamp(raw_timestamp, use_utc, hints):
    return dateparser.parse(raw_timestamp,  settings={'RETURN_AS_TIMEZONE_AWARE': True})
```
together with
```
DATE_DOC_FORMAT = "%Y-%m-%dT%H:%M%Z"

    def timestamp_to_string(self, timestamp):
        return timestamp.strftime(DATE_DOC_FORMAT)
```
works nicely for me here, and seems to be cleaner in general.

**Comment by ownaginatious** [comment]
This is awesome :+1: No idea how I didn't run into this library already, thanks for suggesting it!

Not sure if it's safe to just hand-off detecting the timezone to the library though, given that Facebook likes to use ambiguous ones ones particularly under the English locales (e.g. `CST`). I'll have to look into what `dateparser` does with those.

If everything checks out (and `dateparser` doesn't slow things to a crawl like `arrow` did), then I'll see if I can replace it :)

**Comment by ownaginatious** [comment]
Added in `0.8`. Build is currently broken because of a third-party dependency under certain old versions of Python, but I'm working on it.
