### ISSUE TITLE
Timestamp parsing error

### ISSUE THREAD

**Issue by Andhaa** [ownaginatious/fbchat-archive-parser#16]
Reccieved the following error message: 
Unexpected time format in "5. november 2016 kl. 02:39 UTC+01". This program is optimized to accept English locale time formatting, but will try its best to parse other language time formatting at heavy efficiency costs. Apparently, the time stamp formatting your archive uses has somehow eluded even that.

If you downloaded your Facebook data in a different language, you can try temporarily switching your Facebook language settings to English (US), re-download, and try again. If that doesn't help, then please report this as a bug on the associated GitHub page.

The facebook profile uses Norwegian(Bokmål). 

EDIT: I forgot to mention that your tool looks really awesome and i'm looking forward to testing it!

**Comment by ownaginatious** [comment]
Hi there, thanks for posting this issue! I tried hard-coding support for Norwegian Bokmål based on the sample you provided (... and will eventually try to cover all other supported Facebook languages as well).

Please try with the new version `0.8.post3` and let me know if it fixes things for you :)

**Comment by ownaginatious** [comment]
I'll assume this is working now. Please open another issue if not.

**Comment by Andhaa** [comment]
Yes it worked.  However the test machine crashed as it was running Ubuntu
in VM.  The timestamp parsing worked perfectly though! Thanks alot :)

Den søn. 4. des. 2016, 19.18 skrev Dillon Dixon <notifications@github.com>:

**Comment by ownaginatious** [comment]
That can happen If you have a large conversation history. To get around it, you can extract specific conversations instead using the `-t` switch. I'm trying to think of a better solution for the future.

**Comment by Andhaa** [comment]
Yeah, I'll try on a native install of Ubuntu now and see if it still crashes. Guessing it is a memory choke and a bit more work to fix than hardcoding a timestamp :)
