### ISSUE TITLE
Ambiguous timezone offset found [CDT]?

### ISSUE THREAD

**Issue by ryanknutson** [ownaginatious/fbchat-archive-parser#21]
Hello, so I have tried to run the tool but I keep getting this message

Ambiguous timezone offset found [CDT]. Please re-run the parser with the -z TZ=OFFSET[,TZ=OFFSET2[,...]] flag.(e.g. -t PST=-0800,PDT=-0700). Your options are as follows:
 -> [-0400] for regions like America/Havana, Cuba
 -> [-0500] for regions like America/Merida, America/Menominee, America/Matamoros

I don't live anywhere near Cuba -- I live in Missouri. How do I fix this?

**Comment by ownaginatious** [comment]
You want the second option. The examples given are a random sample of regions within that timezone, and it just so happens all the ones shown here are way down south of the US :p

So re-run the parser like this (looks like I have a typo in the instruction):
```
fbcap ./messages.html -z CDT=-0500,CST=-0600
```

Thank Facebook for choosing the most ambiguous way for recording time stamps :(

**Comment by ryanknutson** [comment]
Thank you!

**Comment by ryanknutson** [comment]
I want going to mention that typo, but I didn't now if it actually wasn't.

On Dec 8, 2016 2:30 PM, wrote:

Thank you!

On Dec 8, 2016 2:10 PM, "Dillon Dixon" <notifications@github.com> wrote:

You want the second option. The examples given are a random sample of
regions within that timezone, and it just so happens all the ones shown
here are way down south of the US :p

So re-run the parser like this (looks like I have a typo in the
instruction):

fbcap ./messages.html -z CDT=-0500,CST=-0600

Thank Facebook for choosing the most ambiguous way for recording time
stamps :(

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ownaginatious/fbchat-archive-parser/issues/21#issuecomment-265841945>,
or mute the thread

**Comment by ownaginatious** [comment]
I'll fix the typo in the next release. Glad to see it worked :)
