### ISSUE TITLE
Does this only work on UNIX based OS

### ISSUE THREAD

**Issue by jchilleo** [ownaginatious/fbchat-archive-parser#22]
I am running into problems with this script finding my python on windows. Does this script only work in UNIX based OS?

**Comment by ownaginatious** [comment]
I haven't personally tested it on Windows, but I believe it should still work. Others on Windows haven't been reporting any issues lately.

How are you installing it?

**Comment by kzisme** [comment]
@jchilleo I don't see why it wouldn't - installing Python and getting the environment setup might be painful compared to a *nix based OS though.  

Awesome project though @ownaginatious

**Comment by jchilleo** [comment]
I followed the readme for install instructions. However I switched to my mac and tried it there and it worked flawlessly.

Not sure what is happening on the windows side, except that I get an error for not finding python. When I run a different script it works perfectly fine :/

**Comment by kzisme** [comment]
@jchilleo Just a random guess, but it depends where you install Python on Windows as well as which version and setting your environment variables up correctly.  I've always found it to be painful :/

Glad it's working for you!

**Comment by ownaginatious** [comment]
I'll try checking things out on Windows later to see if I can figure it out and improve the installing instructions. Thanks for bringing the issue up!

**Comment by ownaginatious** [comment]
Seems like other people have gotten this working on Windows at this point, so I'm going to close the issue.
