### ISSUE TITLE
Not compatible with Hungarian language and/or date format

### ISSUE THREAD

**Issue by Rastamas** [ownaginatious/fbchat-archive-parser#24]
Downloading in Hungarian gives the following error.
Unexpected time format in "2016. j├║nius 16., 9:44 UTC+02". If you downloaded your Facebook data in a language other than English, then it's possible support may need to be added to this tool.

When downloading Hungarian messages in English all our special letters are displayed improperly (á é ö ő ó ú ü ű) 
Thanks for the package though, it's awesome!

**Comment by ownaginatious** [comment]
Thanks for bringing this up! It's expected that the Hungarian date format isn't supported (each one has to be added manually for each language), but that's very odd that the letters are getting corrupted.

Did you happen to open your `messages.htm` file ahead of time and save in a format other than UTF-8?

I will try exporting my own data with the Hungarian locale to see if I can diagnose the issue.

**Comment by Rastamas** [comment]
Just double checked, did not open with anything, just copied out of the zip and into the working folder. Tried opening it with notepad++ and converting it to UTF-8 again but that didn't help either.

**Comment by ownaginatious** [comment]
So I just downloaded my own data in the Hungarian locale, and I see the following:

>Unexpected time format in "2013. július 16., 21:18 PDT". If you downloaded your Facebook data in a language other than English, then it's possible support may need to be added to this tool.
>Please report this as a bug on the associated GitHub page and it will be fixed promptly.

It seems the letters are coming out as expected. I think the issue may be your terminal not being set to UTF-8 encoding.

Anyway, if you pipe your data to a file when extracting, it should have the correct encoding. I'll add Hungarian-style date support now :+1:

**Comment by Rastamas** [comment]
I was just about to write..., starting the console with the proper encoding fixed the issue. Sorry about that.
Thanks for adding the Hungarian date support! :)

**Comment by ownaginatious** [comment]
If you pull the newest version from PyPI (`0.8.post16`) you should be able to parse your data correctly.
