### ISSUE TITLE
PT-BR Time Format

### ISSUE THREAD

**Issue by tloriato** [ownaginatious/fbchat-archive-parser#27]
Sorry to open an issue so broad, but I wanted to know how could I add the timezone for my language, Portuguese-BR?

I understand that I have to modify the Time.py but after that, how could I make sure the script is pulling the info from that file?

Nevertheless, I couldn't comprehend the format. In **time.py** we have:

```
FACEBOOK_TIMESTAMP_FORMATS = [
    ("en_us", "dddd, MMMM D, YYYY [at] h:mmA"),                 # English US (12-hour)
    ("en_us", "dddd, MMMM D, YYYY [at] HH:mm"),                 # English US (24-hour)
    ("en_us", "dddd, D MMMM YYYY [at] HH:mm"),                  # English UK (24-hour)
    ("fr_fr", "dddd D MMMM YYYY, HH:mm"),                       # French (France)
    ("de_de", "dddd, D. MMMM YYYY [um] HH:mm"),                 # German (Germany)
    ("nb_no", "D. MMMM YYYY kl. HH:mm"),                        # Norwegian (Bokmål)
    ("es_es", "dddd, D [de] MMMM [de] YYYY [a las?] H:mm"),     # Spanish (General)
    ("hu_hu", "YYYY. MMMM D., H:mm"),                           # Hungarian
    ("it_it", "dddd D MMMM YYYY [alle ore] H:mm"),              # Italian (Italy)
    
]
```
and from the test html we have:
`<span class="meta">Friday, October 4, 2013 at 10:05pm PDT</span>`

I assume that would be English US (24-hour), right?

In **portuguese** the date looks like that: 
`<span class="meta">Quinta, 9 de junho de 2016 às 19:53 UTC-03</span>`

So...it would be that?
` ("pt_br", "dddd, D [de] MMMM [de] YYYY [às] HH:mm"),              # Portuguese Protype`

How to deal with the **UTC-03?** and add portuguese-br? Thanks!

**Comment by ownaginatious** [comment]
Hi there! Thanks for helping contribute to the locale support 👍

The formatting is supported by the Python library [arrow](https://github.com/crsmithdev/arrow), which uses [these](http://crsmithdev.com/arrow/#tokens) tokens for formatting. The locale for Portuguese is defined [here](https://github.com/crsmithdev/arrow/blob/master/arrow/locales.py#L914).

Not sure if your pattern will work, as what's in `arrow` prefers `quinta-feira` over `Quinta`. Never the less, we could just ignore the day name altogether, as it's not actually necessary to disambiguate the date.

The timezone (in a variety of formats) is resolved automatically, so don't worry about that part.

You can open a PR if you'd like, or I can add the support based on the information you've provided. It would probably be easier to test on your end, given that you already have a `messages.htm` in Brazilian Portuguese. Up to you.

**Comment by tloriato** [comment]
Thanks for the quickly answer!

I'll try to implement it at my end here, how can I test the new time.py? 

ONe more thing...

I have a non-related questions, it's stated that:

> When it's done, it will dump all your conversation history is dumped to **stdout**. 

That would be my CTRL+V? Sorry for the question!

**Comment by ownaginatious** [comment]
Not sure if you're on OS X, Linux, or Windows, so the procedure for setting up the project for development could be different.

General steps are:
1. Fork the repository to your own GitHub account.
2. Clone it to your own machine.
3. Install `virtualenv` if you haven't already.
4. In the directory of the cloned repo, run `virtualenv venv; . ./venv/bin/activate`
5. Run `python ./setup.py develop` to get all the dependencies and setup the project for development.

From that point forward, running `fbcap` while the `venv` is activated will run the code you've modified. Easiest way to test is to simply try running `fbcap messages.htm` and see if it crashes ;)

You should also add a unit test specific to Brazilian Portuguese [here](https://github.com/ownaginatious/fbchat-archive-parser/blob/master/tests/test_timestamps.py).

Dumping to stdout just means it will print to standard output (i.e. your console/terminal).

You can instead dump it to a file by redirecting stdout to a file with `fbcap messages.htm > my_file.txt`

**Comment by tloriato** [comment]
Alright @ownaginatious !

Thanks so much for the help! After playing a little _(downloaded my messages in en-us format)_ here I'll do the PR!
