### ISSUE TITLE
AmbiguousTimeError while trying to run fbcap

### ISSUE THREAD

**Issue by alvinek** [ownaginatious/fbchat-archive-parser#30]
Not much to say about the issue, below there is dump of error message. I'm in Poland timezone.

```
alvinek@linux-1t6h:~/Downloads/facebook-x/html> fbcap ./messages.html
Traceback (most recent call last):
  File "/usr/bin/fbcap", line 9, in <module>
    load_entry_point('fbchat-archive-parser==0.8.post21', 'console_scripts', 'fbcap')()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.4/site-packages/fbchat_archive_parser/main.py", line 11, in <module>
    from .parser import MessageHtmlParser
  File "/usr/lib/python3.4/site-packages/fbchat_archive_parser/parser.py", line 13, in <module>
    from .time import parse_timestamp
  File "/usr/lib/python3.4/site-packages/fbchat_archive_parser/time.py", line 43, in <module>
    tz = pytz_timezone(tz_name).localize(datetime.now() + dt_timedelta(days=d), is_dst=None)
  File "/usr/lib/python3.4/site-packages/pytz/tzinfo.py", line 349, in localize
    raise AmbiguousTimeError(dt)
pytz.exceptions.AmbiguousTimeError: 2017-11-05 00:27:21.444891

```

**Comment by ownaginatious** [comment]
Thanks for reporting this issue! I think I've fixed it; please try version `0.8.post26` from PyPI and let me know if that works for you :)

**Comment by alvinek** [comment]
It works now! But it doesn't show name and surname, it shows this:

`Discovered chat thread with [100002670xxxxxxx@facebook.com, 1000022117xxxxx@facebook.com]...  `
I think Facebook changed something in messages.htm file, but anyway i will wait for result after parsing. :)

**Comment by ownaginatious** [comment]
Yeah, that is unfortunately on Facebook's end. I'm not sure why they sometimes swap names with Facebook emails... it tends to go back and forth if you try to download your data again :/

You may also find that your data is incomplete (i.e. some chat threads missing). Again, that's something weird on Facebook's end.

Only real solution is to try to download your archive a day or two later and hope that whatever you're missing comes back `¯\_(ツ)_/¯`.

**Comment by alvinek** [comment]
Well... it's hard to read that file. I really don't know why they give you a file which is 100 megabytes and it couldn't been opened in browser or notepad. And if opened it's unreadable, even if browser parse it to the end... 

But your script fixes that. Thank you for quick reaction! :)

**Comment by ownaginatious** [comment]
Yeah, I really don't know what Facebook was thinking when they created this. My theory is it was an intern project that made it to production without anyone looking at it, and it doesn't really serve any business purpose and therefore hasn't been fixed.

Glad this tool was able to help you out :)
