### ISSUE TITLE
Only shows Facebook id

### ISSUE THREAD

**Issue by ryanknutson** [ownaginatious/fbchat-archive-parser#35]
It seems like Facebook has changed something in their system, as I cannot use the thread option. It only shows @facebook.com addresses now. An older file I have works just fine.

**Comment by ownaginatious** [comment]
Is it all of them? There are a couple of weird issues with the `messages.htm` file:
- Often not all the conversations there (only trend is it seems to be mostly the more recent ones)
- The names sometimes switch back and forth with Facebook IDs.

Unfortunately, this is an issue on Facebook's end that cannot really be fixed by the tool :/

**Comment by ryanknutson** [comment]
Yes, it is all of them unfortunately. Why does Facebook have to switch things around!

**Comment by ownaginatious** [comment]
Hmm, I just tried downloading a fresh archive and what's even stranger is that it appears the names of the thread participants are now always `@facebook.com` IDs, but the messages themselves for the most part use actual names (minus a few using IDs). You may see the same if you run `fbcap messages.htm -f stats`.

_sigh_... I wish Facebook would just actually fix their message export feature...

**Comment by ownaginatious** [comment]
Technically, I could a feature could be added to attempt to resolve the IDs back into names. It'll be pretty hit or miss though, depending if the users have decided to publicly mask themselves.

**Comment by ryanknutson** [comment]
That's really weird. They should really make a sort-of "offline messenger", so that you can view your messages like if you were actually on Messenger.

**Comment by ryanknutson** [comment]
I would love to work on this project, but sadly I don't know how any of it works haha

**Comment by ownaginatious** [comment]
I just added a feature that uses Facebook to try to convert the IDs back into names.

```bash
 fbcap ./messages.htm -t second --resolve
```

Let me know if that resolves it for you :)

**Comment by ryanknutson** [comment]
Alright, that does work however I can't figure out how to pipe the output because it asks for the username and password.

**Comment by ownaginatious** [comment]
Ah, forgot about that. I think I fixed it. Try version `0.9.post1`.
