### ISSUE TITLE
Czech locale

### ISSUE THREAD

**Issue by mijujda** [ownaginatious/fbchat-archive-parser#39]
Hi, 

I really appreciate your work on this. Could you please add support for czech time formats? I get following error:
`Unexpected time format in "13. b┼Öezen 2014 v 19:42 UTC+01". If you downloaded your Facebook data in a language other than English, then it's possible support may need to be added to this tool.`

The timestamp in czech looks like this:
`<span class="meta">13. březen 2014 v 19:42 UTC+01</span>`
which translates to: "13. march 2014 at 19:42 UTC+01"

I've tried adding support myself, comming up with following format:
`("cs_cz", "D. MMMM YYYY [v] HH:mm")`

and running `python ./setup.py develop` as mentioned in this [comment](https://github.com/ownaginatious/fbchat-archive-parser/issues/27#issuecomment-275176448), but I still get the error (maybe because of non-ASCII characters, such as `ř`).

I would really appreciate if you could look into this, thank you.

Sidenote: I've noticed that, for some reason, facebook for some time used different forms of month names, such as `13. března` instead of `13. březen`, which might cause some issues as `arrow` library supports only one form. This affected only few messages in my file, but might cause trouble when adding official czech locale support (I myself replaced those in Notepad).

**Comment by ownaginatious** [comment]
So the issue with the messed up `ř` is probably due to your terminal being set to some encoding other than `UTF-8`. That shouldn't affect the program itself though in parsing.

As to the `březen` vs `března` issue, I've been expecting that the issue with multiple names for a given month might come up eventually :(

I'll try downloading my own data in the Czech locale and see if I can find a solution. I'll post back here when I've got it sorted out :+1:

**Comment by ownaginatious** [comment]
@mijujda hmm, I just tried using your code and was able to get it to work on my own data by changing the `HH` to just `H` in your parsing string (seems single-digit hours do not have a leading `0` in this locale).

Can you try the same and confirm if that works for you? Not sure the `března` vs `březen` thing is actually an issue here.

**Comment by mijujda** [comment]
Thank you for quick reply, unfortunately changing the time format to `H:mm` didn't seem to solve the problem for me for the first time, however then I tried running it in `virtualenv` and it works! Thank you very much. Could you please advise how to make it work outside `venv`?

**Comment by ownaginatious** [comment]
Great! I updated the tool with Czech support in version `0.9.post10`, so you shouldn't need to hack around it anymore.
