### ISSUE TITLE
time zone error

### ISSUE THREAD

**Issue by solomonvimal** [ownaginatious/fbchat-archive-parser#4]
I get the following error when I run it:

> fbchat_archive_parser.parser.UnexpectedTimeZoneError:

 Expected only PST/PDT time
zones (found Friday, 28 February 2014 at 15:14 UTC+05:30). This is a bug.

>

**Comment by ownaginatious** [comment]
Hi there, thanks for submitting this! I put that exception there on purpose as I live in the PDT/PST timezone and wasn't sure if Facebook gave the same one for everybody's `messages.htm` (considering their headquarters are also in this time zone)... didn't have enough samples to look at.

Anyway, I put in a fix and it should be working now (version 0.5.post6). Please let me know if that fixes the issue for you.
