### ISSUE TITLE
Please add Brazilian portuguese locale support

### ISSUE THREAD

**Issue by spidey** [ownaginatious/fbchat-archive-parser#43]
I'm not into Python, so I'm trying my best to add pt_br support for fbcap. Great tool, thanks for the effort.

Anyway, after checking that arrow already supports pt_pt and pt_br locales, I've added this line to time.py without success, in the FACEBOOK_TIMESTAMP_FORMATS list:

`    ("pt_br", "dddd, D de MMMM de YYYY [às] HH:mm")             # Portuguese BR
`

Unfortunately, after installing the modified package with `pip install . --upgrade`, I get a re.py error:

> Discovered chat thread with [xxxx, yyyy]...Traceback (most recent call last):
>   File "C:\Python27\Scripts\fbcap-script.py", line 11, in <module>
>     load_entry_point('fbchat-archive-parser==0+unknown', 'console_scripts', 'fbcap')()
>   File "c:\python27\lib\site-packages\fbchat_archive_parser\main.py", line 188, in main
>     app.run()
>   File "c:\python27\lib\site-packages\clip.py", line 652, in run
>     self.invoke(self.parse(tokens))
>   File "c:\python27\lib\site-packages\clip.py", line 634, in invoke
>     self._main.invoke(parsed)
>   File "c:\python27\lib\site-packages\clip.py", line 519, in invoke
>     self._callback(**{k: v for k, v in iteritems(parsed) if k not in self._subcommands})
>   File "c:\python27\lib\site-packages\fbchat_archive_parser\main.py", line 125, in fbcap
>     fbch = parser.parse()
>   File "c:\python27\lib\site-packages\fbchat_archive_parser\parser.py", line 102, in parse
>     self._parse_content()
>   File "c:\python27\lib\site-packages\fbchat_archive_parser\parser.py", line 128, in _parse_content
>     self._process_element(pos, element)
>   File "c:\python27\lib\site-packages\fbchat_archive_parser\parser.py", line 257, in _process_element
>     parse_timestamp(e.text, self.use_utc, self.timezone_hints)
>   File "c:\python27\lib\site-packages\fbchat_archive_parser\time.py", line 219, in parse_timestamp
>     timestamp = date_parser.parse(timestamp_string)
>   File "c:\python27\lib\site-packages\fbchat_archive_parser\time.py", line 94, in parse
>     return arrow.get(translated_timestamp, self.timestamp_format).datetime
>   File "c:\python27\lib\site-packages\arrow\api.py", line 23, in get
>     return _factory.get(*args, **kwargs)
>   File "c:\python27\lib\site-packages\arrow\factory.py", line 198, in get
>     dt = parser.DateTimeParser(locale).parse(args[0], args[1])
>   File "c:\python27\lib\site-packages\arrow\parser.py", line 157, in parse
>     match = re.search(final_fmt_pattern, string, flags=re.IGNORECASE)
>   File "c:\python27\lib\re.py", line 146, in search
>     return _compile(pattern, flags).search(string)
>   File "c:\python27\lib\re.py", line 251, in _compile
>     raise error, v # invalid expression
> sre_constants.error: redefinition of group name u'd' as group 3; was group 1
> 

Could you help me? Maybe I'm not installing everything correctly? I'm not well versed in the world of Python, so I can't start debugging the error. When I try running your program directly from source the interpreter complains that the source is including scripts from other directories and that is only allowed in packaged format.

**Comment by ownaginatious** [comment]
You have to use brackets around the `de`s in your pattern. The `d`'s in them are being picked up as meaning something else otherwise. Anything between brackets is escaped.

`("pt_br", "dddd, D [de] MMMM [de] YYYY [às] HH:mm") # Portuguese BR`

The easier way to setup the project for development is to activate your virtual environment and run `python ./setup.py develop`. That should'nt interfere with other installed Python packages.

Let me know if that works and thanks for working on this!

**Comment by spidey** [comment]
Just realized that all literals should be "escaped" using square brackets.

This is a timestamp example:
`Sábado, 29 de junho de 2013 às 23:33 UTC-03
`
This is the adjusted line:
`    ("pt_br", "dddd, D [de] MMMM [de] YYYY [às] HH:mm")         # Portuguese BR
`

But now there is another problem. Facebook doesn't use full weekday names. For example, Tuesday is translated as terça-feira in Portuguese, but Facebook prints Terça only. The abbreviated version is only ter.
Should I sed my whole log or is this viable to do in arrow/fbcap?

**Comment by ownaginatious** [comment]
Easiest way to resolve this is simply remove the day name from the pattern, since it isn't actually used for anything in parsing:
`("pt_br", "D [de] MMMM [de] YYYY [às] HH:mm") # Portuguese BR`

Fortunately month names should parse fine for Portuguese :)

**Comment by spidey** [comment]
Yeah, thank you, that worked. Could you please add Portuguese as a support language? I'm a bit lazy right now to fork and open a merge request.

**Comment by ownaginatious** [comment]
Sure, no problem. Thanks for making the regex! Portuguese (Brazil) is now supported as of `0.9.post19`.

**Comment by spidey** [comment]
Thank you.
