### ISSUE TITLE
Unexpected time format

### ISSUE THREAD

**Issue by t0iska** [ownaginatious/fbchat-archive-parser#52]
Hi, and greetings from Finland! I was trying to parse my messages.htm with this tool but it gave me error about time format, probably because I use Facebook in Finnish, and my downloaded data is also in Finnish. Output I'm getting:

Unexpected time format in "31. heinäkuuta 2016 kello 21:05 UTC+03". If you downl
oaded your Facebook data in a language other than English, then it's possible su
pport may need to be added to this tool.

Please report this as a bug on the associated GitHub page and it will be fixed p
romptly.

**Comment by ownaginatious** [comment]
Thanks for posting this! I have added support for Finnish into version `1.0.post1` :)
