### ISSUE TITLE
Not working with new archive change?

### ISSUE THREAD

**Issue by BCastro1989** [ownaginatious/fbchat-archive-parser#56]
As mentioned in the readme, the file messages.htm no longer has all the messages for everyone in one file, but gives reference to where all those messages are in the /messages directory. The read me makes no indication of weather the program has been modified to reflect this change or if it changes the way I should use it.

I cannot seem to get the program to work with this change.

Running the program with messages.htm gives:

> fbcap ./messages.htm
> /usr/lib/python2.7/dist-packages/cryptography/hazmat/backends/__init__.py:7: UserWarning: Module six was already imported from /home/castro/.local/lib/python2.7/site-packages/six.pyc, but /usr/lib/python2.7/dist-packages is being added to sys.path
>   import pkg_resources
> /usr/lib/python2.7/dist-packages/cryptography/hazmat/backends/__init__.py:7: UserWarning: Module requests was already imported from /usr/local/lib/python2.7/dist-packages/requests/__init__.pyc, but /usr/lib/python2.7/dist-packages is being added to sys.path
>   import pkg_resources
> Traceback (most recent call last):
>   File "/usr/local/bin/fbcap", line 11, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python2.7/dist-packages/fbchat_archive_parser/main.py", line 173, in main
>     app.run()
>   File "/usr/local/lib/python2.7/dist-packages/clip.py", line 652, in run
>     self.invoke(self.parse(tokens))
>   File "/usr/local/lib/python2.7/dist-packages/clip.py", line 634, in invoke
>     self._main.invoke(parsed)
>   File "/usr/local/lib/python2.7/dist-packages/clip.py", line 519, in invoke
>     self._callback(**{k: v for k, v in iteritems(parsed) if k not in self._subcommands})
>   File "/usr/local/lib/python2.7/dist-packages/fbchat_archive_parser/main.py", line 113, in fbcap
>     fbch = parser.parse()
>   File "/usr/local/lib/python2.7/dist-packages/fbchat_archive_parser/parser.py", line 102, in parse
>     self._parse_content()
>   File "/usr/local/lib/python2.7/dist-packages/fbchat_archive_parser/parser.py", line 128, in _parse_content
>     self._process_element(pos, element)
>   File "/usr/local/lib/python2.7/dist-packages/fbchat_archive_parser/parser.py", line 262, in _process_element
>     self.current_sender))
> Exception: Data missing from message. This is a parsingerror: None, None
> 

If I grep to lookup the conversation/file that interests me, and then use that one as my input I get a different error message:

> castro@ezri:~/Desktop/fb/messages$ fbcap 10152874501431571.html
> /usr/lib/python2.7/dist-packages/cryptography/hazmat/backends/__init__.py:7: UserWarning: Module six was already imported from /home/castro/.local/lib/python2.7/site-packages/six.pyc, but /usr/lib/python2.7/dist-packages is being added to sys.path
>   import pkg_resources
> /usr/lib/python2.7/dist-packages/cryptography/hazmat/backends/__init__.py:7: UserWarning: Module requests was already imported from /usr/local/lib/python2.7/dist-packages/requests/__init__.pyc, but /usr/lib/python2.7/dist-packages is being added to sys.path
>   import pkg_resources
> Skipping chat thread with unknown participants...Traceback (most recent call last):
>   File "/usr/local/bin/fbcap", line 11, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python2.7/dist-packages/fbchat_archive_parser/main.py", line 173, in main
>     app.run()
>   File "/usr/local/lib/python2.7/dist-packages/clip.py", line 652, in run
>     self.invoke(self.parse(tokens))
>   File "/usr/local/lib/python2.7/dist-packages/clip.py", line 634, in invoke
>     self._main.invoke(parsed)
>   File "/usr/local/lib/python2.7/dist-packages/clip.py", line 519, in invoke
>     self._callback(**{k: v for k, v in iteritems(parsed) if k not in self._subcommands})
>   File "/usr/local/lib/python2.7/dist-packages/fbchat_archive_parser/main.py", line 113, in fbcap
>     fbch = parser.parse()
>   File "/usr/local/lib/python2.7/dist-packages/fbchat_archive_parser/parser.py", line 102, in parse
>     self._parse_content()
>   File "/usr/local/lib/python2.7/dist-packages/fbchat_archive_parser/parser.py", line 127, in _parse_content
>     parser=parser):
>   File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1271, in next
>     raise e
> xml.etree.ElementTree.ParseError: undefined entity: line 111, column 149

**Comment by ownaginatious** [comment]
The program has been modified to work with the new format. It will not work if you attempt to feed it anything other than a `messages.htm` file.

Given the content of your stack traces, it appears you're using a very old version ever of this tool (literally the first tagged version ever). Did you install it using `pip`? Support was only added for Facebook's new archive format in version `1.1`.

**Comment by BCastro1989** [comment]
I first installed it about 6 months ago. I ran `pip install fbchat-archive-parser` yesterday before trying to use it, figuring there may be an update, but perhaps the install failed or something and I did not realize it!

 I will try again when I get home.

**Comment by ownaginatious** [comment]
Ah, yeah, you need to run `pip install --upgrade fbchat-archive-parser`. `pip` is dumb and won't do anything if it already sees it installed somewhere, regardless of the version.

**Comment by BCastro1989** [comment]
Hmm... I just got that it was all up-to-date, and then the same error as before (parsingerror None, None)

> castro@ezri:~/Desktop/fb/messages$ pip install --upgrade fbchat-archive-parser
> Requirement already up-to-date: fbchat-archive-parser in /home/castro/anaconda2/lib/python2.7/site-packages
> Requirement already up-to-date: arrow==0.9.0 in /home/castro/anaconda2/lib/python2.7/site-packages (from fbchat-archive-parser)
> Requirement already up-to-date: pytz==2016.7 in /home/castro/anaconda2/lib/python2.7/site-packages (from fbchat-archive-parser)
> Requirement already up-to-date: python-dateutil==2.6.0 in /home/castro/.local/lib/python2.7/site-packages (from fbchat-archive-parser)
> Requirement already up-to-date: pyyaml==3.12 in /home/castro/.local/lib/python2.7/site-packages (from fbchat-archive-parser)
> Requirement already up-to-date: click==6.7 in /home/castro/anaconda2/lib/python2.7/site-packages (from fbchat-archive-parser)
> Requirement already up-to-date: babel==2.4.0 in /home/castro/anaconda2/lib/python2.7/site-packages (from fbchat-archive-parser)
> Requirement already up-to-date: bs4==0.0.1 in /home/castro/anaconda2/lib/python2.7/site-packages (from fbchat-archive-parser)
> Requirement already up-to-date: six==1.10.0 in /home/castro/.local/lib/python2.7/site-packages (from fbchat-archive-parser)
> Requirement already up-to-date: beautifulsoup4==4.5.3 in /home/castro/anaconda2/lib/python2.7/site-packages (from fbchat-archive-parser)
> Requirement already up-to-date: requests==2.13.0 in /home/castro/anaconda2/lib/python2.7/site-packages (from fbchat-archive-parser)
> Requirement already up-to-date: colorama==0.3.7 in /home/castro/.local/lib/python2.7/site-packages (from fbchat-archive-parser)

Is there a way for me to check the version I am running of fbcap? I don't see any such info under --help

**Comment by ownaginatious** [comment]
Hmm, my guess is you somehow have two versions installed simultaneously. Did you previously install using `sudo`? If so, you may need to run `sudo pip uninstall fbchat-archive-parser`.

If that doesn't work, what do you get when you run `which fbcap`?

**Comment by ownaginatious** [comment]
Glad you got it working :) And good point; I'll add it to the `README` :+1:
