### ISSUE TITLE
Am getting "Error: Invalid value for "path": Could not open file: ./messages.htm: No such file or directory"

### ISSUE THREAD

**Issue by AFractalThought** [ownaginatious/fbchat-archive-parser#59]
I used this command: 
```
$ fbcap ./messages.htm -f csv -t 'FirstName LastName' -n -r -d my/output/folder
```
Then all proceeded as normal, where I was asked to enter username/ password

```
Facebook username/email: 
Facebook password: 
Repeat for confirmation: 
```

Then got:
```
Usage: fbcap [OPTIONS] PATH
Error: Invalid value for "path": Could not open file: ./messages.htm: No such file or directory
```

**Comment by ownaginatious** [comment]
Looks to me like `./messages.htm` is not actually in your current working directory. If it is, what Python version and operating system are you using?

**Comment by ownaginatious** [comment]
No response, so going to assume that the issue was resolved :ok_hand:
