### ISSUE TITLE
Error at pip install

### ISSUE THREAD

**Issue by wobedi** [ownaginatious/fbchat-archive-parser#60]
Hey guys,

When trying to pip install this from cloud9 IDE I get the following errors:

$ pip install fbchat-archive-parser
Collecting fbchat-archive-parser
  Downloading fbchat_archive_parser-1.2.tar.gz
Collecting arrow==0.9.0 (from fbchat-archive-parser)
  Downloading arrow-0.9.0.tar.gz (86kB)
    100% |████████████████████████████████| 92kB 3.4MB/s 
Collecting babel==2.4.0 (from fbchat-archive-parser)
  Downloading Babel-2.4.0-py2.py3-none-any.whl (6.8MB)
    100% |████████████████████████████████| 6.8MB 213kB/s 
Collecting beautifulsoup4==4.5.3 (from fbchat-archive-parser)
  Downloading beautifulsoup4-4.5.3-py3-none-any.whl (85kB)
    100% |████████████████████████████████| 92kB 9.0MB/s 
Requirement already satisfied: bs4==0.0.1 in /opt/pyenv/versions/3.6.0/lib/python3.6/site-packages (from fbchat-archive-parser)
Requirement already satisfied: click==6.7 in /opt/pyenv/versions/3.6.0/lib/python3.6/site-packages (from fbchat-archive-parser)
Collecting colorama==0.3.7 (from fbchat-archive-parser)
  Downloading colorama-0.3.7-py2.py3-none-any.whl
Collecting python-dateutil==2.6.0 (from fbchat-archive-parser)
  Downloading python_dateutil-2.6.0-py2.py3-none-any.whl (194kB)
    100% |████████████████████████████████| 194kB 4.5MB/s 
Collecting pytz==2016.7 (from fbchat-archive-parser)
  Downloading pytz-2016.7-py2.py3-none-any.whl (480kB)
    100% |████████████████████████████████| 481kB 2.3MB/s 
Collecting pyyaml==3.12 (from fbchat-archive-parser)
  Downloading PyYAML-3.12.tar.gz (253kB)
    100% |████████████████████████████████| 256kB 4.0MB/s 
Collecting requests==2.13.0 (from fbchat-archive-parser)
  Downloading requests-2.13.0-py2.py3-none-any.whl (584kB)
    100% |████████████████████████████████| 593kB 2.1MB/s 
Requirement already satisfied: six==1.10.0 in /opt/pyenv/versions/3.6.0/lib/python3.6/site-packages (from fbchat-archive-parser)
Installing collected packages: python-dateutil, arrow, pytz, babel, beautifulsoup4, colorama, pyyaml, requests, fbchat-archive-parser
  Running setup.py install for arrow ... done
  Found existing installation: pytz 2017.2
    Uninstalling pytz-2017.2:
      Successfully uninstalled pytz-2017.2
  Found existing installation: beautifulsoup4 4.6.0
    Uninstalling beautifulsoup4-4.6.0:
      Successfully uninstalled beautifulsoup4-4.6.0
  Running setup.py install for pyyaml ... error
    Complete output from command /opt/pyenv/versions/3.6.0/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-kgluw1v1/pyyaml/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-xrauev9m-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/yaml
    copying lib3/yaml/emitter.py -> build/lib.linux-x86_64-3.6/yaml
    copying lib3/yaml/tokens.py -> build/lib.linux-x86_64-3.6/yaml
    copying lib3/yaml/loader.py -> build/lib.linux-x86_64-3.6/yaml
    copying lib3/yaml/dumper.py -> build/lib.linux-x86_64-3.6/yaml
    copying lib3/yaml/cyaml.py -> build/lib.linux-x86_64-3.6/yaml
    copying lib3/yaml/serializer.py -> build/lib.linux-x86_64-3.6/yaml
    copying lib3/yaml/error.py -> build/lib.linux-x86_64-3.6/yaml
    copying lib3/yaml/composer.py -> build/lib.linux-x86_64-3.6/yaml
    copying lib3/yaml/parser.py -> build/lib.linux-x86_64-3.6/yaml
    copying lib3/yaml/scanner.py -> build/lib.linux-x86_64-3.6/yaml
    copying lib3/yaml/representer.py -> build/lib.linux-x86_64-3.6/yaml
    copying lib3/yaml/__init__.py -> build/lib.linux-x86_64-3.6/yaml
    copying lib3/yaml/events.py -> build/lib.linux-x86_64-3.6/yaml
    copying lib3/yaml/reader.py -> build/lib.linux-x86_64-3.6/yaml
    copying lib3/yaml/nodes.py -> build/lib.linux-x86_64-3.6/yaml
    copying lib3/yaml/constructor.py -> build/lib.linux-x86_64-3.6/yaml
    copying lib3/yaml/resolver.py -> build/lib.linux-x86_64-3.6/yaml
    warning: build_py: byte-compiling is disabled, skipping.
    
    running build_ext
    creating build/temp.linux-x86_64-3.6
    checking if libyaml is compilable
    clang -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fsanitize=signed-integer-overflow -fsanitize=undefined -ggdb3 -O0 -std=c11 -Wall -Werror -Wextra -Wno-sign-compare -Wshadow -fPIC -I/opt/pyenv/versions/3.6.0/include/python3.6m -c build/temp.linux-x86_64-3.6/check_libyaml.c -o build/temp.linux-x86_64-3.6/check_libyaml.o
    checking if libyaml is linkable
    clang build/temp.linux-x86_64-3.6/check_libyaml.o -lyaml -o build/temp.linux-x86_64-3.6/check_libyaml
    building '_yaml' extension
    creating build/temp.linux-x86_64-3.6/ext
    clang -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fsanitize=signed-integer-overflow -fsanitize=undefined -ggdb3 -O0 -std=c11 -Wall -Werror -Wextra -Wno-sign-compare -Wshadow -fPIC -I/opt/pyenv/versions/3.6.0/include/python3.6m -c ext/_yaml.c -o build/temp.linux-x86_64-3.6/ext/_yaml.o
    In file included from ext/_yaml.c:271:
    ext/_yaml.h:10:9: error: 'PyString_CheckExact' macro redefined [-Werror,-Wmacro-redefined]
    #define PyString_CheckExact PyBytes_CheckExact
            ^
    ext/_yaml.c:139:11: note: previous definition is here
      #define PyString_CheckExact          PyUnicode_CheckExact
              ^
    ext/_yaml.c:1410:17: error: assigning to 'char *' from 'const char *' discards qualifiers [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
      __pyx_v_value = yaml_get_version_string();
                    ^ ~~~~~~~~~~~~~~~~~~~~~~~~~
    ext/_yaml.c:2577:52: error: incompatible pointer types passing 'int (void *, char *, size_t, size_t *)' (aka 'int (void *, char *, unsigned long, unsigned long *)') to parameter of type 'yaml_read_handler_t *' (aka 'int (*)(void *, unsigned char *, unsigned long, unsigned long *)') [-Werror,-Wincompatible-pointer-types]
        yaml_parser_set_input((&__pyx_v_self->parser), __pyx_f_5_yaml_input_handler, ((void *)__pyx_v_self));
                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /usr/include/yaml.h:1368:30: note: passing argument to parameter 'handler' here
            yaml_read_handler_t *handler, void *data);
                                 ^
    ext/_yaml.c:2818:59: error: passing 'char *' to parameter of type 'const unsigned char *' converts between pointers to integer types with different sign [-Werror,-Wpointer-sign]
        yaml_parser_set_input_string((&__pyx_v_self->parser), PyString_AS_STRING(__pyx_v_stream), PyString_GET_SIZE(__pyx_v_stream));
                                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ext/_yaml.h:11:29: note: expanded from macro 'PyString_AS_STRING'
    #define PyString_AS_STRING  PyBytes_AS_STRING
                                ^
    /opt/pyenv/versions/3.6.0/include/python3.6m/bytesobject.h:85:31: note: expanded from macro 'PyBytes_AS_STRING'
    #define PyBytes_AS_STRING(op) (assert(PyBytes_Check(op)), \
                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /usr/include/yaml.h:1342:30: note: passing argument to parameter 'input' here
            const unsigned char *input, size_t size);
                                 ^
    ext/_yaml.c:4572:38: error: passing 'yaml_char_t *' (aka 'unsigned char *') to parameter of type 'const char *' converts between pointers to integer types with different sign [-Werror,-Wpointer-sign]
        __pyx_t_2 = PyUnicode_FromString(__pyx_v_token->data.tag_directive.handle); if (unlikely(!__pyx_t_2)) __PYX_ERR(0, 417, __pyx_L1_error)
                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /opt/pyenv/versions/3.6.0/include/python3.6m/unicodeobject.h:703:17: note: passing argument to parameter 'u' here
        const char *u              /* UTF-8 encoded string */
                    ^
    ext/_yaml.c:4584:38: error: passing 'yaml_char_t *' (aka 'unsigned char *') to parameter of type 'const char *' converts between pointers to integer types with different sign [-Werror,-Wpointer-sign]
        __pyx_t_2 = PyUnicode_FromString(__pyx_v_token->data.tag_directive.prefix); if (unlikely(!__pyx_t_2)) __PYX_ERR(0, 418, __pyx_L1_error)
                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /opt/pyenv/versions/3.6.0/include/python3.6m/unicodeobject.h:703:17: note: passing argument to parameter 'u' here
        const char *u              /* UTF-8 encoded string */
                    ^
    ext/_yaml.c:5444:38: error: passing 'yaml_char_t *' (aka 'unsigned char *') to parameter of type 'const char *' converts between pointers to integer types with different sign [-Werror,-Wpointer-sign]
        __pyx_t_2 = PyUnicode_FromString(__pyx_v_token->data.alias.value); if (unlikely(!__pyx_t_2)) __PYX_ERR(0, 448, __pyx_L1_error)
                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /opt/pyenv/versions/3.6.0/include/python3.6m/unicodeobject.h:703:17: note: passing argument to parameter 'u' here
        const char *u              /* UTF-8 encoded string */
                    ^
    ext/_yaml.c:5518:38: error: passing 'yaml_char_t *' (aka 'unsigned char *') to parameter of type 'const char *' converts between pointers to integer types with different sign [-Werror,-Wpointer-sign]
        __pyx_t_2 = PyUnicode_FromString(__pyx_v_token->data.anchor.value); if (unlikely(!__pyx_t_2)) __PYX_ERR(0, 451, __pyx_L1_error)
                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /opt/pyenv/versions/3.6.0/include/python3.6m/unicodeobject.h:703:17: note: passing argument to parameter 'u' here
        const char *u              /* UTF-8 encoded string */
                    ^
    ext/_yaml.c:5592:38: error: passing 'yaml_char_t *' (aka 'unsigned char *') to parameter of type 'const char *' converts between pointers to integer types with different sign [-Werror,-Wpointer-sign]
        __pyx_t_2 = PyUnicode_FromString(__pyx_v_token->data.tag.handle); if (unlikely(!__pyx_t_2)) __PYX_ERR(0, 454, __pyx_L1_error)
                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /opt/pyenv/versions/3.6.0/include/python3.6m/unicodeobject.h:703:17: note: passing argument to parameter 'u' here
        const char *u              /* UTF-8 encoded string */
                    ^
    ext/_yaml.c:5604:38: error: passing 'yaml_char_t *' (aka 'unsigned char *') to parameter of type 'const char *' converts between pointers to integer types with different sign [-Werror,-Wpointer-sign]
        __pyx_t_2 = PyUnicode_FromString(__pyx_v_token->data.tag.suffix); if (unlikely(!__pyx_t_2)) __PYX_ERR(0, 455, __pyx_L1_error)
                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /opt/pyenv/versions/3.6.0/include/python3.6m/unicodeobject.h:703:17: note: passing argument to parameter 'u' here
        const char *u              /* UTF-8 encoded string */
                    ^
    ext/_yaml.c:5716:38: error: passing 'yaml_char_t *' (aka 'unsigned char *') to parameter of type 'const char *' converts between pointers to integer types with different sign [-Werror,-Wpointer-sign]
        __pyx_t_2 = PyUnicode_DecodeUTF8(__pyx_v_token->data.scalar.value, __pyx_v_token->data.scalar.length, ((char *)"strict")); if (unlikely(!__pyx_t_2)) __PYX_ERR(0, 460, __pyx_L1_error)
                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /opt/pyenv/versions/3.6.0/include/python3.6m/unicodeobject.h:1287:17: note: passing argument to parameter 'string' here
        const char *string,         /* UTF-8 encoded string */
                    ^
    ext/_yaml.c:7424:42: error: passing 'yaml_char_t *' (aka 'unsigned char *') to parameter of type 'const char *' converts between pointers to integer types with different sign [-Werror,-Wpointer-sign]
            __pyx_t_4 = PyUnicode_FromString(__pyx_v_tag_directive->handle); if (unlikely(!__pyx_t_4)) __PYX_ERR(0, 574, __pyx_L1_error)
                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /opt/pyenv/versions/3.6.0/include/python3.6m/unicodeobject.h:703:17: note: passing argument to parameter 'u' here
        const char *u              /* UTF-8 encoded string */
                    ^
    ext/_yaml.c:7436:42: error: passing 'yaml_char_t *' (aka 'unsigned char *') to parameter of type 'const char *' converts between pointers to integer types with different sign [-Werror,-Wpointer-sign]
            __pyx_t_4 = PyUnicode_FromString(__pyx_v_tag_directive->prefix); if (unlikely(!__pyx_t_4)) __PYX_ERR(0, 575, __pyx_L1_error)
                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /opt/pyenv/versions/3.6.0/include/python3.6m/unicodeobject.h:703:17: note: passing argument to parameter 'u' here
        const char *u              /* UTF-8 encoded string */
                    ^
    ext/_yaml.c:7655:38: error: passing 'yaml_char_t *' (aka 'unsigned char *') to parameter of type 'const char *' converts between pointers to integer types with different sign [-Werror,-Wpointer-sign]
        __pyx_t_4 = PyUnicode_FromString(__pyx_v_event->data.alias.anchor); if (unlikely(!__pyx_t_4)) __PYX_ERR(0, 586, __pyx_L1_error)
                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /opt/pyenv/versions/3.6.0/include/python3.6m/unicodeobject.h:703:17: note: passing argument to parameter 'u' here
        const char *u              /* UTF-8 encoded string */
                    ^
    ext/_yaml.c:7749:40: error: passing 'yaml_char_t *' (aka 'unsigned char *') to parameter of type 'const char *' converts between pointers to integer types with different sign [-Werror,-Wpointer-sign]
          __pyx_t_4 = PyUnicode_FromString(__pyx_v_event->data.scalar.anchor); if (unlikely(!__pyx_t_4)) __PYX_ERR(0, 591, __pyx_L1_error)
                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /opt/pyenv/versions/3.6.0/include/python3.6m/unicodeobject.h:703:17: note: passing argument to parameter 'u' here
        const char *u              /* UTF-8 encoded string */
                    ^
    ext/_yaml.c:7790:40: error: passing 'yaml_char_t *' (aka 'unsigned char *') to parameter of type 'const char *' converts between pointers to integer types with different sign [-Werror,-Wpointer-sign]
          __pyx_t_4 = PyUnicode_FromString(__pyx_v_event->data.scalar.tag); if (unlikely(!__pyx_t_4)) __PYX_ERR(0, 594, __pyx_L1_error)
                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /opt/pyenv/versions/3.6.0/include/python3.6m/unicodeobject.h:703:17: note: passing argument to parameter 'u' here
        const char *u              /* UTF-8 encoded string */
                    ^
    ext/_yaml.c:7811:38: error: passing 'yaml_char_t *' (aka 'unsigned char *') to parameter of type 'const char *' converts between pointers to integer types with different sign [-Werror,-Wpointer-sign]
        __pyx_t_4 = PyUnicode_DecodeUTF8(__pyx_v_event->data.scalar.value, __pyx_v_event->data.scalar.length, ((char *)"strict")); if (unlikely(!__pyx_t_4)) __PYX_ERR(0, 595, __pyx_L1_error)
                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /opt/pyenv/versions/3.6.0/include/python3.6m/unicodeobject.h:1287:17: note: passing argument to parameter 'string' here
        const char *string,         /* UTF-8 encoded string */
                    ^
    ext/_yaml.c:8179:40: error: passing 'yaml_char_t *' (aka 'unsigned char *') to parameter of type 'const char *' converts between pointers to integer types with different sign [-Werror,-Wpointer-sign]
          __pyx_t_4 = PyUnicode_FromString(__pyx_v_event->data.sequence_start.anchor); if (unlikely(!__pyx_t_4)) __PYX_ERR(0, 620, __pyx_L1_error)
                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /opt/pyenv/versions/3.6.0/include/python3.6m/unicodeobject.h:703:17: note: passing argument to parameter 'u' here
        const char *u              /* UTF-8 encoded string */
                    ^
    ext/_yaml.c:8220:40: error: passing 'yaml_char_t *' (aka 'unsigned char *') to parameter of type 'const char *' converts between pointers to integer types with different sign [-Werror,-Wpointer-sign]
          __pyx_t_4 = PyUnicode_FromString(__pyx_v_event->data.sequence_start.tag); if (unlikely(!__pyx_t_4)) __PYX_ERR(0, 623, __pyx_L1_error)
                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /opt/pyenv/versions/3.6.0/include/python3.6m/unicodeobject.h:703:17: note: passing argument to parameter 'u' here
        const char *u              /* UTF-8 encoded string */
                    ^
    fatal error: too many errors emitted, stopping now [-ferror-limit=]
    20 errors generated.
    error: command 'clang' failed with exit status 1
    
    ----------------------------------------
**Command "/opt/pyenv/versions/3.6.0/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-kgluw1v1/pyyaml/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-xrauev9m-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-kgluw1v1/pyyaml/**

**Comment by ownaginatious** [comment]
Looks like this is blowing up installing the `pyyaml` dependency. I've swapped it for `pyyaml`, which is significantly easier to install. Please try again with the latest `master`.

**Comment by ownaginatious** [comment]
Err, nevermind, had to undo it (the new library had even more problems...). Looks like cloud9 has some sort of issue with the C dependencies... I'm honestly not sure how to fix it as I've never used cloud9 before.

You could just remove the `pyyaml` dependency from the `requirements.txt` and kill the `yaml` writer if you really want it to work.

**Comment by wobedi** [comment]
Thanks for the swift response!

As suggested by you I installed it manually now without the yaml writer &
dependency - all works fine so far, thanks! Will report this issue to
Cloud9 as well.

FYI: I am going to use your library for a tool that periodically analyses
my message history and reminds me to follow up with (selected) friends that
I haven't been in touch with for x days (eg 90 days). It's a final project
for a coding class but I probably will use it myself later on and share
with friends as well.

Best,
Yanick

*Yanick Steinbeck*
Skype: YanickSTE
*Find me on LinkedIn*
<http://ch.linkedin.com/pub/yanick-steinbeck/86/b09/248>
