### ISSUE TITLE
Silent failure when parsing

### ISSUE THREAD

**Issue by willium** [ownaginatious/fbchat-archive-parser#62]
It's worked previously, but now does not (I think there is a new facebook archive format as of the last few weeks, it worked fine ~1 month ago). Running 
`fbcap ./html/messages.htm`
yields:
```
----------------------------------------er]...
 Conversation history of Will Strimling
----------------------------------------

   There's nothing here!
```

**Comment by ownaginatious** [comment]
Ah, looks like the format of `messages.htm` changed (again...). Shouldn't be too difficult to fix; I'll post an update when it works again :+1:

**Comment by ownaginatious** [comment]
Hi there, this should be fixed now. Please try the latest version: `1.3.1`
