### ISSUE TITLE
Error with newly downloaded FB archive.

### ISSUE THREAD

**Issue by kjetilhoiby** [ownaginatious/fbchat-archive-parser#64]
I just downloaded my fb data just as the previous issue was raised, and waited until the fix for the January '18 format was released. 
I've updated fbcap to 1.3.1, and get this error:

> Traceback (most recent call last):
>   File "/usr/local/bin/fbcap", line 9, in <module>
>     load_entry_point('fbchat-archive-parser==1.3.1', 'console_scripts', 'fbcap')()
>   File "/Library/Python/2.7/site-packages/click/core.py", line 722, in __call__
>     return self.main(*args, **kwargs)
>   File "/Library/Python/2.7/site-packages/click/core.py", line 697, in main
>     rv = self.invoke(ctx)
>   File "/Library/Python/2.7/site-packages/click/core.py", line 895, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/Library/Python/2.7/site-packages/click/core.py", line 535, in invoke
>     return callback(*args, **kwargs)
>   File "/Library/Python/2.7/site-packages/fbchat_archive_parser/main.py", line 119, in fbcap
>     progress_output=not noprogress, use_utc=utc, name_resolver=resolve)
>   File "/Library/Python/2.7/site-packages/fbchat_archive_parser/parser.py", line 517, in parse
>     return parser(handle, *args, **kwargs).parse()
>   File "/Library/Python/2.7/site-packages/fbchat_archive_parser/parser.py", line 258, in parse
>     self.parse_impl()
>   File "/Library/Python/2.7/site-packages/fbchat_archive_parser/parser.py", line 504, in parse_impl
>     participants = self.parse_participants(unescaped)
>   File "/Library/Python/2.7/site-packages/fbchat_archive_parser/parser.py", line 350, in parse_participants
>     if not participants.text:
> AttributeError: 'str' object has no attribute 'text'

**Comment by ownaginatious** [comment]
Ah, didn't do enough Python 2 specific testing. Should be fixed now in `1.3.2` :+1:
