### ISSUE TITLE
./messages.htm - could not find path

### ISSUE THREAD

**Issue by holmstrom** [ownaginatious/fbchat-archive-parser#66]
Hello, 

When I type fbcap ./messages.htm I get the respond "Error: Invalid value for "path": Could not open file: ./messages: Is a directory" 

Do you know what the solution could be? 

I have also tried to open the file in the terminal and make small modifications when typing the command.

**Comment by ownaginatious** [comment]
Are you sure you have the correct path? The instructions in the readme assume you have changed to the root of your extracted Facebook archive.

**Comment by holmstrom** [comment]
I cd to the direct facebook file (where the photos, videos, messages are in) in the terminal and then I am running the command. Am I doing it wrong? 
I see now, that I have a file called fbMessages.txt - but it is empty? Just got that file.

**Comment by ownaginatious** [comment]
Sorry, the `messages.htm` file is actually located under `html/`.

Try this from the root of your extracted archive: `fbcap html/messages.htm`

**Comment by holmstrom** [comment]
Thank you very much! I worked - fantastic! 
One quick bonus question (sorry to bother you). 

Is it possible to get more statistic?

**Comment by ownaginatious** [comment]
Right now, the only stats are those produced by `fbcap /path/to/messages.htm -f stats`. If you have any ideas of what other statistics might be useful, I can see what I could possibly implement.

**Comment by holmstrom** [comment]
You're genius. 
- It could be interesting to split it to gender. I know this will be very difficult, as it would have to know which names is male or female. But would be usefull to extract valid data
- A longer list (Top 50) 
- Top 300 frequent words (could be useful for implementing the data to chatbots) 

But thank you very much for your fast and excellent help. Very useful!
