### ISSUE TITLE
json file and elasticsearch

### ISSUE THREAD

**Issue by ufo56** [ownaginatious/fbchat-archive-parser#67]
Hi

Im exploring elasticsearch and kibana and found out this excellent parser when i was looking around in github.

It would be nice import facebook messages to elasticsearch and draw a nice graphs and stats about conversations, maybe :P 

One big problem is elastic does not like this kind json formating what this script makes..
Is there any simple way to make this work or it's not so easy ? I was just thinking it would be nice dataset to play around. If my idea is stupid then just ignore me :D 

I tried to import and modify fb parser json using this sample data as example but did not get any great success.
https://www.elastic.co/guide/en/kibana/current/tutorial-load-dataset.html

**Comment by ownaginatious** [comment]
Hi there! That's a good idea! I'm not familiar with `elasticsearch` really, but it shouldn't be _too_ difficult to add another output format. However, looking at the documentation you sent, shouldn't it just be a matter of writing a mapping?

**Comment by ownaginatious** [comment]
Going to close this due to inactivity. Please feel free to re-open if you have more questions.
