### ISSUE TITLE
html5lib issue (

### ISSUE THREAD

**Issue by christensen5** [ownaginatious/fbchat-archive-parser#68]
I'm getting the following error when trying to run fbcap from terminal:

module 'html5lib.treebuilders' has no attribute '_base'

I gather this is due to some issue with newer versions of html5lib, but even downgrading to older versions (1.0b8 for example) doesnt seem to fix the problem.

**Comment by ownaginatious** [comment]
Hmm, could you provide a stack trace along with your version of Python and operating system?

**Comment by christensen5** [comment]
Apologies - I've found the problem. I had performed a user install of fbchat-archive-parser and was accidentally downgrading the system python rather than my user python installation. Running `pip install --user --upgrade html5lib==1.0b8` solved the issue.

**Comment by ownaginatious** [comment]
Ah good to here that fixed it!
