### ISSUE TITLE
Parse specific message html file

### ISSUE THREAD

**Issue by conwayzhu** [ownaginatious/fbchat-archive-parser#69]
It seems that the format has changed from messages.htm to a messages directory messages/convo_id.html. How do we run the fbchat parser on a specific message file? The output seems to be {"user": null, "threads": []}

**Comment by ownaginatious** [comment]
The `messages.htm` file should still be there under the `html/` folder (unless the format changed super recently). It makes references to the `messages/` folder and automatically traverses the references. Please try that. You can use the filtering flags to get specific conversations.

**Comment by conwayzhu** [comment]
Thanks! Appreciate the help

**Comment by ownaginatious** [comment]
No problem, glad that worked :)
