### ISSUE TITLE
Parse just my own messages 

### ISSUE THREAD

**Issue by burstMembrane** [ownaginatious/fbchat-archive-parser#71]
Hi, I am trying use your tool to create a dictionary json file to train a chatbot to speak like me. I'm using this code
https://github.com/thePetrMarek/Bot_U
Which isn't working because it parses conversations based upon the old messages.htm structure pre Oct 2017. Do you have any tips on how to use your tool to create a json file of just my messages and responses?
Thanks in advance for your help!

**Comment by ownaginatious** [comment]
Could you elaborate? I'm not sure what you mean by just your messages and responses.

I suppose if you literally just want stuff you said, you could do something like this: `fbcap messages.htm -f json > history.json` and then run this:

```python
import json

with open('./history.json', 'r') as f:
    data = json.loads(f.reads())

things_said_by_me = []

user = data['user']
for t in data['threads']:
    for m in t['messages']:
        if m['sender'] == user:
           things_said_by_me += [m['message']]
with open('./my_messages.json', 'w') as f:
    f.write(json.dumps(things_said_by_me))
```

This is pretty inefficient from a memory standpoint, but it should get the job done.

**Comment by burstMembrane** [comment]
Hi,
Sorry if I'm a bit vague just beginning with python etc. Yeah I think that
is exactly what I need, to parse just my language to train a model to speak
like me using a sequence to sequence model. Thanks a lot for that snippet!

**Comment by ownaginatious** [comment]
Cool, please open a new issue if you need anything else :+1:
