### ISSUE TITLE
Anonymous (Facebook User) threads are grouped together

### ISSUE THREAD

**Issue by hc98br** [ownaginatious/fbchat-archive-parser#73]
Hi,

Thanks for your great script - works really well, but I have hit on a problem...

In my archive there are about 65 conversation treads with people who I'm no longer connected to on Facebook, so they just show as "Facebook User".  The parser is grouping all the messages from these threads together (assuming they are the same person).

It would be better if they could be separate - is that easy to fix?

Many thanks,

Ben

**Comment by ownaginatious** [comment]
Hi there! Thanks for pointing this out :+1: Yep, that's a bug. I was able to reproduce the problem and fix it. The `Facebook User`s are now broken out into `Unknown user #001` incrementing depending on how many `Facebook User` conversations you have.

Please try the latest version: `1.3.4` and close the issue if everything works :)

**Comment by hc98br** [comment]
Perfect - excellent work - thank you!
