### ISSUE TITLE
Count of all threads?

### ISSUE THREAD

**Issue by mpentler** [ownaginatious/fbchat-archive-parser#75]
Is there a way to make the stats view show the total number of threads (either individual sessions, combined threads, etc)?

I’m trying to combine a bunch of already-written tools with some more code of my own to make a single script to analyse a downloaded data dump from FB (given recent revelations...)

**Comment by ownaginatious** [comment]
I think so. I'm going to try to rewrite the stats thing this weekend to include more useful data and output to more machine consumable formats (e.g. JSON).

**Comment by mpentler** [comment]
That sounds great! Right now what I’m doing is parsing your output for the word “Discovered” :-P

**Comment by ownaginatious** [comment]
@mpentler I just made a new PR with much more statistics info than was there previously + JSON/YAML output support. Let me know what you think of that and if you have any suggestions :+1:

**Comment by ownaginatious** [comment]
No response, so I'll assume it looks good :+1:

**Comment by mpentler** [comment]
Afraid not :( I’ve been ill for a week or so. I’ll try and have a look tomorrow. Much better now.

Sent from my iPhone

On 9 Apr 2018, at 22:02, Dillon Dixon <notifications@github.com<mailto:notifications@github.com>> wrote:


No response, so I'll assume it looks good 👍

**Comment by ownaginatious** [comment]
No problem, just let me know if there is anything else you would like me to add in a new issue if you see anything.

**Comment by mpentler** [comment]
Just to say this is great and now I don’t have to do a bunch of shit in my code. Thanks.
