### ISSUE TITLE
Add support for 1337 speak

### ISSUE THREAD

**Issue by TheNiceGuy** [ownaginatious/fbchat-archive-parser#77]
Yeah, I do use that and Facebook won't generate another archive with a different language for now. I got a time format like `r3b3cc4 b14k d4y, n0v3mb3r 17, 2017 @ 2:31pm EST`. Is the time format the only thing to fix for the language? I might bother to fix it maybe.

**Comment by ownaginatious** [comment]
heh, interesting. Yeah, you can technically just add it as another language. You will most likely have to do the same thing the guy did in #76 to get the month mappings down.

**Comment by TheNiceGuy** [comment]
Thank you, I got something working. Pull request should be coming soon.
